### ISSUE TITLE
More examples for where filtering in Document API

### ISSUE THREAD

**Issue by michelderu** [stargate/docs#134]
From several sources I've had the request to extend the documentation for filtering on the Document API. Especially filtering on multiple fields and filtering on deep nested JSON structures.

**Comment by dimas-b** [comment]
What is available here will probably be affected by https://github.com/stargate/stargate/issues/1063 and https://github.com/stargate/stargate/issues/828 in the positive sense, i.e. expanding the scope of what is available.

**Comment by ivansenic** [comment]
I will paste here some examples which are not yet covered by the documentation, so that @polandll can move this forward:

1. multiple conditions on the same field - `where={ "product.price": { "$gt": 100, "$lt": 1000}}`
2. path segments, use `,` to match two or more paths - `where={ "product.price,discountPrice": { "$gt": 100}}` - this will match any product having `price` or `discountPrice` greater that 100
3. array elements matching - `where={ "product.reviews.[0].status": { "$eq": "APPROVED"}}` - finds any product where first review has status approved
4. array globs (wildcards) - `where={ "product.reviews.[*].status": { "$eq": "APPROVED"}}` - finds any product where any review has status approved
5. path globs (wildcards) - `where={ "product.reviews.[*].*": { "$eq": "APPROVED"}}` - finds any product where any review has any field with value approved
6. mix all of those above is possible as well:  `where={ "*.test,reviews.[*].rating": { "$gt": 4}}` - matches document that on the second level has test or review with rating above 4

@polandll I am here for any question.

**Comment by polandll** [comment]
Also need to update the document yaml file with new predicates.

**Comment by polandll** [comment]
Document v2 API: $eq, $ne, $in, $nin, $gt, $lt, $gte, $lte, $exists.

Related to #134.

**Comment by debdeep-das** [comment]
> I will paste here some examples which are not yet covered by the documentation, so that @polandll can move this forward:
> 
> 1. multiple conditions on the same field - `where={ "product.price": { "$gt": 100, "$lt": 1000}}`
> 2. path segments, use `,` to match two or more paths - `where={ "product.price,discountPrice": { "$gt": 100}}` - this will match any product having `price` or `discountPrice` greater that 100
> 3. array elements matching - `where={ "product.reviews.[0].status": { "$eq": "APPROVED"}}` - finds any product where first review has status approved
> 4. array globs (wildcards) - `where={ "product.reviews.[*].status": { "$eq": "APPROVED"}}` - finds any product where any review has status approved
> 5. path globs (wildcards) - `where={ "product.reviews.[*].*": { "$eq": "APPROVED"}}` - finds any product where any review has any field with value approved
> 6. mix all of those above is possible as well:  `where={ "*.tests,reviews.[*].rating": { "$gt": 4}}` - matches document that on the second level has test or review with rating above 4
> 
> @polandll I am here for any question.

Does the wild character at all work? 
Below is my document and I am trying `where={"alpha.[*]":{"$eq":"xyz"}}` but it does not return aything
```
{
    "id": "1234",
    "vowels": "aeu",
    "alpha":[
        "xyz",
        "efgh"
    ],
    "new": [
        {"name":"nam1"},
        {"name":"nam2"}
    ]
}
```

**Comment by ivansenic** [comment]
> > I will paste here some examples which are not yet covered by the documentation, so that @polandll can move this forward:
> > 
> > 1. multiple conditions on the same field - `where={ "product.price": { "$gt": 100, "$lt": 1000}}`
> > 2. path segments, use `,` to match two or more paths - `where={ "product.price,discountPrice": { "$gt": 100}}` - this will match any product having `price` or `discountPrice` greater that 100
> > 3. array elements matching - `where={ "product.reviews.[0].status": { "$eq": "APPROVED"}}` - finds any product where first review has status approved
> > 4. array globs (wildcards) - `where={ "product.reviews.[*].status": { "$eq": "APPROVED"}}` - finds any product where any review has status approved
> > 5. path globs (wildcards) - `where={ "product.reviews.[*].*": { "$eq": "APPROVED"}}` - finds any product where any review has any field with value approved
> > 6. mix all of those above is possible as well:  `where={ "*.tests,reviews.[*].rating": { "$gt": 4}}` - matches document that on the second level has test or review with rating above 4
> > 
> > @polandll I am here for any question.
> 
> Does the wild character at all work?
> Below is my document and I am trying `where={"alpha.[*]":{"$eq":"xyz"}}` but it does not return aything
> 
> ```
> {
>     "id": "1234",
>     "vowels": "aeu",
>     "alpha":[
>         "xyz",
>         "efgh"
>     ],
>     "new": [
>         {"name":"nam1"},
>         {"name":"nam2"}
>     ]
> }
> ```

@debdeep-das At the moment wild-cards can not be used at the leaf name, meaning that can not be last in the search path:
* `something.[*].field` - does work
* `something.[*]` - does not work

Unfortunately my comment that you referenced has a non-working example `where={ "product.reviews.[*].*": { "$eq": "APPROVED"}}`. However, this is something we can easily support and we already have a ticket for this: https://github.com/stargate/stargate/issues/1247

**Comment by polandll** [comment]
https://github.com/stargate/docs/pull/217
